version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_multi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_MULTIPLE_DATABASES: notification,bifast
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/01-init-multiple-databases.sh
      - ./db-specific-scripts.sh:/docker-entrypoint-initdb.d/02-db-specific-scripts.sh
      - ../../src/go/services/notification-service/migrations/001_create_notifications_table.sql:/docker-entrypoint-initdb.d/init-db-notification.sql
      - ../../src/go/services/mock-bifast-service/migrations/001_create_table.sql:/docker-entrypoint-initdb.d/init-db-bifast.sql
      - ../../src/go/services/mock-bifast-service/migrations/002_seeding_bank_accounts.sql:/docker-entrypoint-initdb.d/seeding-db-bifast.sql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-root} -d bifast"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"  # SMTP port
      - "1080:1080"  # Web interface port
    restart: unless-stopped

volumes:
  postgresql_data: